<a href="https://colab.research.google.com/github/MhyrnB/Data-Sci/blob/main/Mhyrn_Bazile's_Copy_of_Hahn_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [1]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


*Here we've comanded the algorithm to give us 100 numbers without including 100.*

In [2]:
for i in range(5,8):
    print(i)

5
6
7


*Here this function gives us the minimum value, the minimum value plus 1, and the minimum value - 1. Naturally it wouldn't include the last number (8)*

In [3]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


*Here we once more aks the algorithm for a range of numbers, it'll give s three numebr without including three. This time around we asked the algorithm to print "Test Number: ", by placing it before the i and in quotation marks, before the ranges (0,1,2)*

### Functions

In [4]:
def square(x):
    return x**2

*Here we simply gave the algorithm the definition of squaring, that way when we write "square" the algotithm will do the function for any given integer.*

In [5]:
square(5)

25

*Due to the previous information, the algorithm is able to square 5, giving us 25*

In [6]:
square(square(2))

16

*Here we're just squaring twice; 2^2 = 4^2 = 16*

In [7]:

square(square(square(2)))


256

*here we squared three times; 2^2 = 4^2 = 16^2 = 256*

In [8]:
square(123456)

15241383936

In [9]:
square(square(5))

625

*We continue to practice squaring functions*

In [10]:
def add_two(x):
    return x+2

*Here we define add_two as +2 to any given varibale (x). Now the algorithm know what to do if we simple code "add_two" with a variable*

In [11]:
add_two(5)

7

*Once more the preparations above is demonstrated here as the algorithm added 2 to 5 and gave us 7*

In [12]:
square(add_two(5))

49

*Here we wrote both functions. Thanks to the us running the information on the algorithim before hand, the algorithn can added 2 to 5, which = 7, then squared 7  giving us 49.*

### Logical Branching

In [13]:
choice = "apple"

*here we gave the word choice a "defintion"*

In [14]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


*With this function we say if the choice is apple then the algorithm should print out "you choose apples". If the choice is anything but apples then the algorithm will print out "You did not choose apples"*

In [15]:
choice = "orange"

*Here we introdce another choice*

In [16]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


*Here the result will say "you did not choose apples" because right above the choice was orange*

In [17]:
choice = "apple"

In [18]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


*This function tells the algorithm if the choice is apples it should say "you choose apples. Thank you, shop again!", if the choice is orange the algorithm should say "You choose oranges. Thank you, shop again!" and if it is anything but these two choice then the algorithm should say "You did not choose apples or ornages. Thank you, shop again!". (When doing this make sure you pay close attention to your spacing and spelling of course)* 

### User Input

In [19]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): 


*Now this is cool, it allows the user to actually type out their answer then after it processes the text.*

In [20]:
choice

''

In [21]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You did not choose apples or oranges.


*Here, once more, we are telling the algorithm the response to put out when the choice is either apple, oranges, or something else.*

#### Coins

In [22]:
import numpy as np

*(hope it's ok I added this, it wouldn't allow me to run np.random.random(10) with defining "np.") Here we just gave numpy a shorter name so that the algorithm recognizes when it's being used with another function*

In [23]:
np.random.random(10)

array([0.83856541, 0.43607992, 0.0351538 , 0.45405871, 0.40652938,
       0.215849  , 0.3966201 , 0.72237135, 0.44989393, 0.78485699])

*Here is a new function that will always give us a random number that is less than 1 every time we run it.*

In [24]:
np.random.random() > 0.5

True

*Here we ask the algorithm if the random number is greater than 0.5; the answer will change between True and false because the function "np.random.random" will always give us a different number every time we run it.*

In [25]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

*Following the "np.random.random" function we are now introducing a new funtion: "flip_coin". So we tell the algorithim if the random integer is greater than 0.5 then the solution is "Heads" and if the random integer is anything else then the solution is "Tails".*

In [26]:
flip_coin()

Tails


*Here we can keep on flipping the coin and it'll either give us "Heads" or "Tails" every time we run it*

### Graphics Output

In [27]:
from IPython.core.display import display, HTML

*This is a function that allows us to write a bolded title without the usual drop down that we do when we put this (#) symbol*

In [28]:
display(HTML('<h1>Hello, world!</h1>'))

*This time we gave "HTML" a title to display (Hello, worls!) and it did.*

In [29]:
def coin():
  return np.random.randint(2)

*Here we defined coin and associated it with the function "np.random.randint" which will give us a response between the two ( thats why theres a 2).*

In [30]:
coin()

0

*This function will alternate between 0 and 1 as options for the coin flip*

In [31]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

*Here we use the function "img src =" to add a url and recieve an image*

In [32]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

*Here we give the solutions, "heads" or "tails", images to be associated with by the algorithm.*

In [33]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [34]:
show_img(heads)

In [35]:
show_img(tails)

*Those three functions above are used to tell the algorithm what image to produce, heads or tails.*

In [36]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

*Here this function tells the algorithm to either display heads or tails with space to provide a function for the algorithm to use*

In [37]:
flip_coin()

*From this function the response will alternate between heads or tails*

In [38]:
for i in range(5):
    flip_coin()

*Here we asked for 5 differnet possibilities, as though we flipped a coin 5 times.*

In [39]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

*From this function the response will alternate between heads or tails*

### Cards

In [40]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

*Here the function shuffle is introduced. It causese the arrangement of numbers to no longer be displayed in numerical patters. Instead the numbers will be scrattered.* 

In [41]:
a = np.arange(52)

*here we made a = an arangement of numbers counting up to 52 withot including 52*

In [42]:
shuffle(a)

array([25, 41, 51, 39, 47, 31, 19, 27,  9, 23,  5, 42,  6, 35, 20, 46, 36,
       22, 11, 44,  1, 34, 33, 12, 48, 26, 16, 32, 29, 38, 21, 43, 18, 28,
       40, 24,  0, 10, 15, 50,  8, 14, 37, 49, 13, 17,  3,  4,  2,  7, 45,
       30])

With the help of all of the previous codes, a can now equal a shuffled list of 52 numbers withot including 52** 

In [43]:
np.random.permutation(52)

array([33,  5, 39, 30, 15, 35, 31, 36,  1, 41,  6, 23, 17,  9, 45, 11, 27,
       18, 24, 48, 29, 25, 26,  2, 22, 44, 34, 20, 51, 14, 37, 43,  3, 42,
       47, 21,  8, 49, 16, 10, 40, 13, 38,  0,  7,  4, 12, 50, 28, 32, 46,
       19])

*This function cause the original data to remain the same while returning a new variable.*

### Speed Test

In [44]:
%%timeit
shuffle(a)

201 µs ± 30.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [45]:
%%timeit
np.random.permutation(52)

3.53 µs ± 222 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
import numpy as np

In [47]:
np.random.permutation(52)

array([19, 14, 26, 25, 12, 48, 27, 46, 50, 15, 18,  6, 13, 29,  7, 49, 36,
       20, 40, 11, 35, 47, 21,  2, 28, 32, 42,  5, 33,  0, 43, 44,  9, 38,
       30, 31, 24, 16, 45,  4, 10, 51,  1, 37, 39, 22,  3, 23,  8, 34, 41,
       17])

*This function cause the original data to remain the same while returning a new variable.*

In [48]:
cards = np.random.permutation(52)

*Now we gave a name to np.random.permutation(25). The algorithm now knows if we write the word "cards" we want the np.random.permtation(25).*

In [49]:
cards

array([ 8, 21, 37, 30, 23, 15, 34,  1, 48, 47, 16, 29, 49, 28, 12, 40, 19,
        7, 20, 17, 50, 32, 43, 10,  0,  9, 51, 24, 27, 22, 38, 25, 35, 33,
       26, 11, 13,  2, 31, 42, 45, 44,  5, 18,  3, 39, 36,  6, 14, 41, 46,
        4])

*The information listed above is displayed here*

In [50]:
cards[0]

8

In [51]:
cards[1]

21

In [52]:
cards[2]

37

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

*As we've done in the past we wrote "<img src=" then inserted the URL of teh image we want the algorithm to put on display.*

In [53]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

*Here a new function is introduced: np.arange.reshape. The number after "arrange" signifies the amount of numbers we want without including 52. The first number after "reshape" tells the algorithm how many rows we want and the second number tells the algorithm how many columns we want. *

In [54]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

*The added function "13%" causes the algorithm to print out 13 numbers, without the numebr 13, in an arrangement of 52 numbers in 13 columns and 4 rows.* 

In [55]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [56]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

Here we name the four rows, provided by "reshape(4,13), suits with a label for each row. We also named the 13 colmumns, provided by "reshape(4,13)", names with lables for each column.*  

In [57]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

*We defined suits and names as the cards brought up by the functions "card_number//13" and "card_number%13".*  

In [58]:
card_name(0)

'Ace of Clubs'

*Here you can see that the function for suits and cards have been combined so that the algorithm can name exactly what the very first card is. This is all thanks to the functions above that gave the algorithm the informaton it needed to give this output.*

In [59]:
card_name(51)

'King of Diamonds'

In [60]:
cards = np.random.permutation(52)

In [61]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

*Here we assign the words top_of_deck, second_card_in_deck, and last_card_in_deck with a card number from the URL. This way the algorithm can give us an output of the name of each specific card (top_of_deck, second_card_in_deck, and last_card_in_deck)*

In [62]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Jack of Hearts', 'Five of Hearts', 'Two of Hearts')

*Here we displayed the functions we wrote above* 

In [63]:
for i in range(5):
    print(card_name(cards[i]))

Jack of Hearts
Five of Hearts
Ten of Clubs
Ace of Hearts
King of Diamonds


*Here with the command "card_name" we ask the algorithm to print out the name of each card and by writting "for i in range(5):" in the begining we ask the algorithm to print out the names of 5 cards.*

In [64]:
for i in range(15):
    print(card_name(cards[i]))

Jack of Hearts
Five of Hearts
Ten of Clubs
Ace of Hearts
King of Diamonds
Five of Clubs
Jack of Clubs
King of Hearts
Seven of Hearts
Six of Clubs
Four of Spades
Eight of Diamonds
Nine of Diamonds
Two of Clubs
Nine of Hearts


*Here with the command "card_name" we ask the algorithm to print out the name of each card and by writting "for i in range(15):" in the begining we ask the algorithm to print out the names of 15 cards.*

https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [65]:
?

In [66]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [67]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [68]:
i = np.random.randint(4)
j = np.random.randint(13)

*here we are giving the algorithm what to use to identify a card based on it's placement.*

In [69]:
i,j

(2, 4)

In [70]:
suit[i]

's'

In [71]:
card[j]

'5'

In [72]:
from IPython.core.display import display, HTML

In [73]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [74]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [75]:
show_img(img)

In [76]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [77]:
card_image(3)

'k4'

In [78]:
img = card_url_head + card_image(3) + card_url_tail

In [79]:
show_img(img)

In [80]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)